name: Sync Upstream

on:
  schedule:
    - cron: '0 */6 * * *'  # every 6 hours
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Sync fork
        uses: tgymnich/fork-sync@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          upstream_repository: GrapheneOS/Messaging
          upstream_branch: main
          target_branch: main
          
